name: wodoxo_api
description: "A new Flutter plugin project."
version: 0.0.1
homepage:

environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  json_annotation: ^4.8.1
  path: ^1.8.2 # 1.8.2 for flutter_test as of 2023-04-06
  meta: ^1.8.0
  freezed: ^2.4.6
  dio: ^5.4.0
  connectivity: ^3.0.6
  vexana: ^3.5.4
  

dev_dependencies:
  analyzer: ^6.0.0
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  freezed_annotation: ^2.4.1
  lints: ^3.0.0
  test: ^1.21.4
  coverage: ^1.6.2
